### ISSUE TITLE
Use other shell

### ISSUE THREAD

**Issue by Zwer2k** [iulian-radu-at/taskfile-launcher#2]
The launcher executes all commands in Powerschell. Is there any way to switch to git bash?

**Comment by iulian-radu-at** [comment]
Hi @Zwer2k,

Please install v1.2.0 as I added there the support to define your own shell but it is also documented which shell is started in the terminal.

When you define Git Bash as your default shell for the VSCode Terminal then the tasks should start using it.

Cheers,
Iulian
