### ISSUE TITLE
request: show tasks in VSCode's "Run task" list

### ISSUE THREAD

**Issue by tennox** [iulian-radu-at/taskfile-launcher#3]
Would be great to be able to quickly run tasks via VSCode's integrated tasks menu :thinking: 
![image](https://github.com/iulian-radu-at/taskfile-launcher/assets/2084639/5584a96b-2480-4a94-a3f8-a05185496fc4)

The other taskfile extension has it, but is a bit broken and unmaintained :cry: 
https://github.com/paulvarache/vscode-taskfile

**Comment by iulian-radu-at** [comment]
Hi @tennox,

I added your requested feature in 1.3.0.
Please test it and give me feedback if it is what you wanted.

Cheers,
Iulian
